const express = require('express');
const app = express();
app.use(express.json());
app.use(express.static(__dirname));
let bookings = [];
app.get('/api/bookings', (req, res) => res.json(bookings));
app.post('/api/bookings', (req, res) => { bookings.push(req.body); res.sendStatus(201); });
app.delete('/api/bookings/:id', (req, res) => { bookings = bookings.filter(b => b.id !== req.params.id); res.sendStatus(200); });
app.get('*', (req, res) => res.sendFile(__dirname + '/index.html'));
app.listen(process.env.PORT || 3000);
